#!/usr/bin/env bash
# ----------------------------------------------------------------------------
# scripts/build-valuation-dossier.sh
#
# Génère le dossier de valorisation (apport en nature) à plat dans
# `dossier-valorisation/`. Idempotent : peut être relancé à volonté.
#
# Contenu produit :
#   1-presentation/          docs/README.md, docs/ARCHITECTURE.md (copies brutes)
#   2-coverage/              rapport Vitest HTML (si présent dans coverage/),
#                            fallback vers docs/audit/coverage/
#   3-audit-securite/        npm-audit.json + licenses.json
#   4-cabinet/               copie figée de docs/cabinet/
#   5-historique-git/        git log + git shortlog + tags + commits Wave
#   6-inventaire/            cloc (si dispo) + npm ls --depth=0 + npm ls --all
#   manifest.txt             liste exhaustive horodatée
#
# La génération PDF (pandoc) est tentée si pandoc est installé, sinon ignorée.
# Sortie gitignorée (cf. .gitignore : `dossier-valorisation/`).
# ----------------------------------------------------------------------------
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/dossier-valorisation"
TS="$(date -u +"%Y-%m-%dT%H-%M-%SZ")"

echo "Building valuation dossier in: $OUT"
rm -rf "$OUT"
mkdir -p "$OUT"/{1-presentation,2-coverage,3-audit-securite,4-cabinet,5-historique-git,6-inventaire}

# --- 1. Présentation ---
if [ -d "$ROOT/docs" ]; then
  cp -R "$ROOT/docs/." "$OUT/1-presentation/" 2>/dev/null || true
fi

# Optionnel: PDF via pandoc
if command -v pandoc >/dev/null 2>&1 && [ -f "$ROOT/docs/README.md" ]; then
  pandoc "$ROOT/docs/README.md" -o "$OUT/1-presentation/presentation.pdf" \
    --metadata title="Kora — Dossier de valorisation" 2>/dev/null || true
fi

# --- 2. Coverage ---
if [ -d "$ROOT/coverage" ]; then
  cp -R "$ROOT/coverage/." "$OUT/2-coverage/" 2>/dev/null || true
  echo "Coverage source: local coverage/ (regenerated by npm run test:coverage)" \
    > "$OUT/2-coverage/SOURCE.txt"
elif [ -d "$ROOT/docs/audit/coverage" ]; then
  cp -R "$ROOT/docs/audit/coverage/." "$OUT/2-coverage/" 2>/dev/null || true
  echo "Coverage source: docs/audit/coverage/ (versioned snapshot)" \
    > "$OUT/2-coverage/SOURCE.txt"
  echo "To produce a fresh report locally, run: npm run test:coverage" \
    >> "$OUT/2-coverage/SOURCE.txt"
else
  echo "Coverage report missing. Run: npm run test:coverage" \
    > "$OUT/2-coverage/README.txt"
fi

# --- 3. Audit sécurité ---
( cd "$ROOT" && npm audit --json > "$OUT/3-audit-securite/npm-audit.json" 2>/dev/null ) || true
# license-checker peut prendre quelques minutes (parcourt node_modules)
if command -v npx >/dev/null 2>&1; then
  echo "  - extracting licenses (this may take a few minutes)..."
  ( cd "$ROOT" && npx --yes license-checker --json > "$OUT/3-audit-securite/licenses.json" 2>/dev/null ) || \
    echo '{"error":"license-checker failed or not installed"}' > "$OUT/3-audit-securite/licenses.json"
fi

# Pointeur vers les rapports d'audit canoniques versionnés
if [ -d "$ROOT/docs/audit" ]; then
  cp "$ROOT/docs/audit/SECURITY_REMEDIATION_REPORT.md" "$OUT/3-audit-securite/" 2>/dev/null || true
  cp "$ROOT/docs/audit/COVERAGE_REPORT.md" "$OUT/3-audit-securite/" 2>/dev/null || true
  cp "$ROOT/docs/audit/DATA_TRUTH_REPORT.md" "$OUT/3-audit-securite/" 2>/dev/null || true
  cp "$ROOT/docs/audit/PROJECT_AUDIT_NOTES.md" "$OUT/3-audit-securite/" 2>/dev/null || true
fi

# --- 4. Cabinet ---
# Copie figée du dossier destiné au cabinet d'évaluation (docs/cabinet/)
if [ -d "$ROOT/docs/cabinet" ]; then
  cp -R "$ROOT/docs/cabinet/." "$OUT/4-cabinet/" 2>/dev/null || true
else
  echo "docs/cabinet/ not found. Skipping." > "$OUT/4-cabinet/README.txt"
fi

# --- 5. Historique Git ---
( cd "$ROOT" && git log --stat --pretty=fuller HEAD < /dev/null > "$OUT/5-historique-git/git-log.txt" ) || true
# Note: `git shortlog` lit stdin si on n'explicite pas une révision.
# On lui passe HEAD explicitement et on ferme stdin pour éviter tout blocage.
( cd "$ROOT" && git shortlog -sne HEAD < /dev/null > "$OUT/5-historique-git/contributors.txt" ) || true
( cd "$ROOT" && git tag --list < /dev/null > "$OUT/5-historique-git/tags.txt" ) || true
# Sous-ensemble Wave 1 + Wave 2 (mai 2026 et +)
( cd "$ROOT" && git log --stat --since="2026-05-01" HEAD < /dev/null > "$OUT/5-historique-git/git-history-wave.txt" ) || true
# One-line summary pour vue d'ensemble
( cd "$ROOT" && git log --oneline HEAD < /dev/null > "$OUT/5-historique-git/git-log-oneline.txt" ) || true

# --- 6. Inventaire code & deps ---
if command -v cloc >/dev/null 2>&1; then
  cloc "$ROOT/src" "$ROOT/server.cjs" > "$OUT/6-inventaire/cloc.txt" 2>/dev/null || true
else
  echo "cloc not installed -- install with: brew install cloc" > "$OUT/6-inventaire/cloc.txt"
fi
( cd "$ROOT" && npm ls --all --json > "$OUT/6-inventaire/npm-ls.json" 2>/dev/null ) || true
( cd "$ROOT" && npm ls --depth=0 > "$OUT/6-inventaire/npm-ls-top.txt" 2>&1 ) || true

# Volumétrie src/ rapide (pour traçabilité du dossier 01-perimetre.md §1.7)
{
  echo "Volumétrie src/ (find + wc) — généré $TS"
  echo
  ( cd "$ROOT" && find src -type f \( -name '*.ts' -o -name '*.tsx' \) -print0 \
    | xargs -0 wc -l 2>/dev/null | tail -1 ) || echo "n/a"
} > "$OUT/6-inventaire/src-volumetry.txt"

# --- Manifest horodaté ---
{
  echo "Kora Digital Pilot — dossier de valorisation"
  echo "Généré: $TS"
  echo "Package: $(cd "$ROOT" && node -p "require('./package.json').name + ' v' + require('./package.json').version" 2>/dev/null || echo n/a)"
  echo "Branche: $(cd "$ROOT" && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo n/a)"
  echo "Commit:  $(cd "$ROOT" && git rev-parse HEAD 2>/dev/null || echo n/a)"
  echo "Tag courant (le plus proche): $(cd "$ROOT" && git describe --tags --always 2>/dev/null || echo n/a)"
  echo ""
  echo "Contenu (3 niveaux):"
  ( cd "$OUT" && find . -maxdepth 3 -type f | sort )
} > "$OUT/manifest.txt"

echo "Dossier valorisation produit dans: $OUT"
